// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueViagem.Data;

#nullable disable

namespace QueViagem.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QueViagem.Model.Destinos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cidade");

                    b.Property<string>("ImagemDestino")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("imagem_destino");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pais");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Amsterdã",
                            ImagemDestino = "https://www.melhoresdestinos.com.br/wp-content/uploads/2019/02/passagens-aereas-amsterda-capa2019-03-820x430.jpg",
                            Pais = "Holanda",
                            Valor = 3100m
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Paris",
                            ImagemDestino = "https://viagemeturismo.abril.com.br/wp-content/uploads/2016/11/thinkstockphotos-4549879531.jpeg?quality=90",
                            Pais = "França",
                            Valor = 3600m
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Santiago",
                            ImagemDestino = "https://www.vrbo.com/pt-br/dicas-viagem/wp-content/uploads/67PoRLlKbEDl0ZGSgeKs2E/eff02c3a63848a35d322b172ebee7645/AdobeStock_209940755.jpeg",
                            Pais = "Chile",
                            Valor = 3300m
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Buenos Aires",
                            ImagemDestino = "https://aguiarbuenosaires.com/wp-content/uploads/2015/10/Obelisco-Mapa-de-Buenos-Aires-Foto-Wikipedia2-800x600.jpg",
                            Pais = "Argentina",
                            Valor = 2950m
                        },
                        new
                        {
                            Id = 5,
                            Cidade = "Fernando de Noronha",
                            ImagemDestino = "https://www.melhoresdestinos.com.br/wp-content/uploads/2022/02/fernando-noronha-capa-2022-820x430.jpg",
                            Pais = "Brasil",
                            Valor = 5500m
                        },
                        new
                        {
                            Id = 6,
                            Cidade = "Orlando",
                            ImagemDestino = "https://res.klook.com/image/upload/c_fill,w_1265,h_712/q_80/activities/alg3puq4hmpeobqhumjd.webp",
                            Pais = "EUA",
                            Valor = 4850m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
